- name: For collect script
  hosts: all
  become: yes
  become_user: megh_support
  tasks:
    - name: Create scripts directory
      ansible.builtin.file:
        path: /home/megh_support/scripts
        state: directory

    - name: Copy collect.sh script
      ansible.builtin.copy:
        src: /home/akushwaha/collect.sh
        dest: /home/megh_support/scripts/collect.sh

    - name: Set execute permission on collect.sh
      ansible.builtin.file:
        path: /home/megh_support/scripts/collect.sh
        mode: "+x"